// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private Tile[] tiles;
	/**
	 * 
	 */
	private Settlement[] verticies;
	/**
	 * 
	 */
	private Road[] edges;

	/**
	 * 
	 */
	public void Board() {
	}

	/**
	 * 
	 * @param player 
	 * @param vertex 
	 */
	public void placeSettlement(Player player, int vertex) {
	}

	/**
	 * 
	 * @param player 
	 * @param edge 
	 */
	public void placeRoad(Player player, int edge) {
	}

	/**
	 * 
	 * @param vertex 
	 * @return 
	 */
	private boolean vertexOpen(int vertex) {
	}

	/**
	 * 
	 * @param edge 
	 * @return 
	 */
	private boolean edgeOpen(int edge) {
	}

	/**
	 * 
	 * @return 
	 */
	public Tile getTile() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getVertex() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getEdge() {
	}
}
