// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	public class Class1 {
	};

	/**
	 * 
	 */
	public class Class2 {
	};

	/**
	 * 
	 */
	public class Class3 {
	};

	/**
	 * 
	 */
	private String userColor;
	/**
	 * 
	 */
	private String victoryPoints = 0;
	/**
	 * 
	 */
	private ResourceType[] resources;

	/**
	 * 
	 * @param userColor 
	 */
	public void Player(String userColor) {
	}

	/**
	 * 
	 * @return 
	 */
	public int takeTurn() {
	}

	/**
	 * 
	 * @return 
	 */
	private int rollDice() {
	}

	/**
	 * 
	 * @param roll 
	 */
	private void collectResource(int roll) {
	}

	/**
	 * 
	 */
	private void chooseMove() {
	}

	/**
	 * 
	 * @return 
	 */
	private boolean canBuildRoad() {
	}

	/**
	 * 
	 * @return 
	 */
	private boolean canBuildSettlement() {
	}

	/**
	 * 
	 * @return 
	 */
	private boolean canBuildCity() {
	}

	/**
	 * 
	 * @return 
	 */
	private int options() {
	}

	/**
	 * 
	 * @param option 
	 */
	private void spend(int option) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
	}

	/**
	 * 
	 * @param point 
	 */
	public void addVictoryPoints(int point) {
	}
}
