// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Road {
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private int edge;

	/**
	 * 
	 * @param owner 
	 * @param edge 
	 */
	public void Road(Player owner, int edge) {
	}

	/**
	 * 
	 * @return 
	 */
	public Player getRoad() {
	}
}
