// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Settlement {
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private String level;
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private int vertex;

	/**
	 * 
	 * @param owner 
	 * @param vertex 
	 */
	public void Settlement(Player owner, int vertex) {
	}

	/**
	 * 
	 */
	public void upgrade() {
	}

	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getLevel() {
	}
}
