// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Catan {
	/**
	 * 
	 */
	private Player[] players;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private int currentTurn;
	/**
	 * 
	 */
	private int maxRounds;

	/**
	 * 
	 */
	public void Catan() {
	}

	/**
	 * 
	 */
	public void play() {
	}

	/**
	 * 
	 * @param win 
	 */
	private void checkWin(boolean win) {
	}

	/**
	 * 
	 */
	private void displayWInner() {
	}

	/**
	 * 
	 */
	private void playRound() {
	}

	/**
	 * 
	 */
	private void startGame() {
	}
}
