// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private ResourceType resource;
	/**
	 * 
	 */
	private int number;
	/**
	 * 
	 */
	private int[] adjacentVerticies;

	/**
	 * 
	 * @param resource 
	 * @param number 
	 */
	public void Tile(ResourceType resource, int number) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getVerticies() {
	}

	/**
	 * 
	 * @param vertex 
	 * @return 
	 */
	public Tile[] getAdjacentTIles(int vertex) {
	}
}
